### PR TITLE
Support parsing NativePixelData when it appears multiple times in a DICOM

### LINKED ISSUE #65: Error: Encountered odd length
Another issue when scanning many DICOMs:

```
Encountered odd length (vl=13945) when reading explicit VR SQ for tag (6003,1010)[private] (file offset 1752)
Encountered odd length (vl=27975) when reading explicit VR SQ for tag (6003,1010)[private] (file offset 1752)
Encountered odd length (vl=286383071) when reading implicit VR 'UN' for tag (1111,11e3)[private] (file offset 5382)
Encountered odd length (vl=419395) when reading explicit VR OW for tag (6000,3000)[??] (file offset 13496)
```

### LINKED ISSUE #77: ERROR ReadBytes
`ERROR ReadBytes: requested 2, available 0 (file offset 65274)`

I haven't had a chance to look into it yet, but I've attached 3 example files and will try to get more info sometime soon.

[examples.zip](https://github.com/suyashkumar/dicom/files/4665083/examples.zip)

Data Citation:
_Kinahan, Paul; Muzi, Mark; Bialecki, Brian; Coombs, Laura. (2017). Data from ACRIN-FLT-Breast. The Cancer Imaging Archive. http://doi.org/10.7937/K9/TCIA.2017.ol20zmxg_

### LINKED ISSUE #82: ERROR dicom.ReadElement: Undefined length disallowed
This error occurs [here](https://github.com/suyashkumar/dicom/blob/master/parse.go#L351) in parser.go in the ParseNext() function. Something odd that I don't completely understand is that the tags reported in the error, at least for the two example errors below, don't exist in the file (they aren't printed out with [dcmdump](https://support.dcmtk.org/docs/dcmdump.html)). 

**Example errors:**
- ERROR dicom.ReadElement: Undefined length disallowed for VR=\u0000\u0000, tag (0000,0000)[CommandGroupLength] (file offset 61170)
- ERROR dicom.ReadElement: Undefined length disallowed for VR=\u0007\u0000, tag (ffdc,ffc4)[??] (file offset 61006)

**Sample files**
[issue82.zip](https://github.com/suyashkumar/dicom/files/4704720/issue82.zip)

### PR DESCRIPTION
**Pull request by suyashkumar**
This fixes #77 and appears to work on provided DICOMs. This is a relatively quick fix, that does seem to get the job done. There are some minor improvements that can be made in future PRs, but it will be best to get these changes in to unblock future work. 

This also appears to fix #82, and fix #65 (we are able to parse those images without errors).

For most of the provided images, the issue was that an icon image sequence could appear in the DICOMs in addition to the primary PixelData. When reading that particular image sequence, a different set of metadata tags need to be used (instead of the global ones, which apply only to the core PixelData).

There may be additional work to fully and correctly parsing icon image sets (most of the icons seem to be unpopulated in the sample images), but this change will at least prevent the parser from failing on DICOMs like this.

### CODE REVIEW

**Comment by suyashkumar** [comment]
Many thanks to @IChocked and @wkoszek for their sample DICOMs and bug reports to help track this down!

**Comment by IChocked** [comment]
@suyashkumar Thanks for merging these changes! Would it be possible to git tag this version? I thought it was included in [release 0.4.3](https://github.com/suyashkumar/dicom/releases/tag/v0.4.3), but I realize now that it's not

**Comment by suyashkumar** [comment]
@IChocked, just [released and tagged v0.4.4](https://github.com/suyashkumar/dicom/releases/tag/v0.4.4). Thanks!

**Comment by IChocked** [comment]
Thank you! It is much appreciated :)

**Pull request merged**
