### PR TITLE
Export writeElement and readElement

### PR DESCRIPTION
**Pull request by kristianvalind**
I'm working on a port of the [grailbio/go-netdicom](https://github.com/grailbio/go-netdicom) package to use your maintained and more idiomatic implementation instead of [grailbio/go-dicom](https://github.com/grailbio/go-dicom). To be able to encode and decode DIMSE messages, I need to use per-element writing and reading. Rather than reimplementing this functionality myself, I propose exporting the readElement and writeElement functions so that go-netdicom or other packages that require low-level DICOM functionality may benefit.

### CODE REVIEW

**Comment by suyashkumar** [comment]
Thanks @kristianvalind! Question for you--would it not be possible to use the [`Parser.Next()` pattern](https://pkg.go.dev/github.com/suyashkumar/dicom#Parser.Next) to do element-by-element reading?

Would a similar Writer API help on the writing side?

Just curious--any more context on how you're approaching this would be helpful! 

On my side, I don't think this is a huge deal, but also, I'm careful to export more ways to read an element because I'd like there to be one (or maybe two) canonical exported ways to do something (like read or write) in this library.

**Comment by kristianvalind** [comment]
The functionality I need is single element reading and writing, so `Parser.Next()` seems like a good fit on the reading side. For writing, a Writer type with a similar API would probably be a cleaner solution than just exporting writeElement. 

What would be the best way to implement such an API? I think it would be relatively easy to create a new Writer struct type with methods calling existing non-exported writing functions, but that would not follow the pattern of the Parser type, and might not be the most elegant way...

**Comment by kristianvalind** [comment]
I'm closing this pull request and will submit another with a Writer struct implementation suggestion.

**Comment by estergoldberg** [comment]
Hi @kristianvalind - do you have a netdicom project that use @suyashkumar's  go-dicom package?
Did you really implement code for dicom query that using latest go-dicom package?
I need to implement 'Modality worklist' and also want to use netdicom and go-dicom packages
Thanks in advanced.

**Comment by kristianvalind** [comment]
@estergoldberg Unfortunately, no. 

I started a port of [grailbio/go-netdicom](https://github.com/grailbio/go-netdicom) to use @suyashkumar's go-dicom, but I haven't touched it in almost 2 years. If you want to have a look, some incomplete feature branches are [available](https://github.com/kristianvalind/go-netdicom-port/branches).

My goal was something that would be useful for MW, but I ended up calling `findscu` from dcmtk via `os/exec` instead.

**Comment by estergoldberg** [comment]
Thanks anyway, will take a look on your branches.

**Pull request closed without merging**
